# Generated by Django 4.1.2 on 2022-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeankersIWApp', '0002_cliente_compra_sneaker_precio_alter_sneaker_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_Cliente',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_Sneaker',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='compra',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
