# Generated by Django 4.1.2 on 2022-11-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeankersIWApp', '0003_compra_id_cliente_compra_id_sneaker_compra_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='descripcion',
            field=models.CharField(default='', max_length=300),
        ),
    ]
